use movies;

drop table if exists movies;

CREATE TABLE movies(
film_id int auto_increment primary key,
title VARCHAR(100),
released_year INT,
genre VARCHAR(20),
runtime INT,
overview VARCHAR(500),
actors JSON,
director VARCHAR(50),
poster VARCHAR(200),
video_file VARCHAR(100)
);

insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('The Shawshank Redemption', 1994, 'Drama', 142, 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', '["Tim Robbins", "Morgan Freeman"]', 'Frank Darabont', 'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('The Godfather', 1972, 'Crime', 175, 'An organized crime dynasty''s aging patriarch transfers control of his clandestine empire to his reluctant son.', '["Marlon Brando", "Al Pacino"]', 'Francis Ford Coppola', 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UY98_CR1,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('The Dark Knight', 2008, 'Action', 152, 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.', '["Christian Bale", "Heath Ledger"]', 'Christopher Nolan', 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('The Godfather: Part II', 1974, 'Crime', 202, 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.', '["Al Pacino", "Robert De Niro"]', 'Francis Ford Coppola', 'https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UY98_CR1,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('12 Angry Men', 1957, 'Crime', 96, 'A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.', '["Henry Fonda", "Lee J. Cobb"]', 'Sidney Lumet', 'https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('The Lord of the Rings: The Return of the King', 2003, 'Action', 201, 'Gandalf and Aragorn lead the World of Men against Sauron''s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.', '["Elijah Wood", "Viggo Mortensen"]', 'Peter Jackson', 'https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('Pulp Fiction', 1994, 'Crime', 154, 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', '["John Travolta", "Uma Thurman"]', 'Quentin Tarantino', 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UY98_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('Schindler''s List', 1993, 'Biography', 195, 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.', '["Liam Neeson", "Ralph Fiennes"]', 'Steven Spielberg', 'https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('Inception', 2010, 'Action', 148, 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.', '["Leonardo DiCaprio", "Joseph Gordon-Levitt"]', 'Christopher Nolan', 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('Fight Club', 1999, 'Drama', 139, 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.', '["Brad Pitt", "Edward Norton"]', 'David Fincher', 'https://m.media-amazon.com/images/M/MV5BMmEzNTkxYjQtZTc0MC00YTVjLTg5ZTEtZWMwOWVlYzY0NWIwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('The Lord of the Rings: The Fellowship of the Ring', 2001, 'Action', 178, 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.', '["Elijah Wood", "Ian McKellen"]', 'Peter Jackson', 'https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('Forrest Gump', 1994, 'Drama', 142, 'The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate and other historical events unfold through the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.', '["Tom Hanks", "Robin Wright"]', 'Robert Zemeckis', 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY98_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('Il buono, il brutto, il cattivo', 1966, 'Western', 161, 'A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.', '["Clint Eastwood", "Eli Wallach"]', 'Sergio Leone', 'https://m.media-amazon.com/images/M/MV5BOTQ5NDI3MTI4MF5BMl5BanBnXkFtZTgwNDQ4ODE5MDE@._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('The Lord of the Rings: The Two Towers', 2002, 'Action', 179, 'While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron''s new ally, Saruman, and his hordes of Isengard.', '["Elijah Wood", "Ian McKellen"]', 'Peter Jackson', 'https://m.media-amazon.com/images/M/MV5BZGMxZTdjZmYtMmE2Ni00ZTdkLWI5NTgtNjlmMjBiNzU2MmI5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('The Matrix', 1999, 'Action', 136, 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.', '["Lilly Wachowski", "Keanu Reeves"]', 'Lana Wachowski', 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('Goodfellas', 1990, 'Biography', 146, 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.', '["Robert De Niro", "Ray Liotta"]', 'Martin Scorsese', 'https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('Star Wars: Episode V - The Empire Strikes Back', 1980, 'Action', 124, 'After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued by Darth Vader and a bounty hunter named Boba Fett all over the galaxy.', '["Mark Hamill", "Harrison Ford"]', 'Irvin Kershner', 'https://m.media-amazon.com/images/M/MV5BYmU1NDRjNDgtMzhiMi00NjZmLTg5NGItZDNiZjU5NTU4OTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('One Flew Over the Cuckoo''s Nest', 1975, 'Drama', 133, 'A criminal pleads insanity and is admitted to a mental institution, where he rebels against the oppressive nurse and rallies up the scared patients.', '["Jack Nicholson", "Louise Fletcher"]', 'Milos Forman', 'https://m.media-amazon.com/images/M/MV5BZjA0OWVhOTAtYWQxNi00YzNhLWI4ZjYtNjFjZTEyYjJlNDVlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('Hamilton', 2020, 'Biography', 160, 'The real life of one of America''s foremost founding fathers and first Secretary of the Treasury, Alexander Hamilton. Captured live on Broadway from the Richard Rodgers Theater with the original Broadway cast.', '["Lin-Manuel Miranda", "Phillipa Soo"]', 'Thomas Kail', 'https://m.media-amazon.com/images/M/MV5BNjViNWRjYWEtZTI0NC00N2E3LTk0NGQtMjY4NTM3OGNkZjY0XkEyXkFqcGdeQXVyMjUxMTY3ODM@._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('Gisaengchung', 2019, 'Comedy', 132, 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.', '["Kang-ho Song", "Lee Sun-kyun"]', 'Bong Joon Ho', 'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('Soorarai Pottru', 2020, 'Drama', 153, 'Nedumaaran Rajangam "Maara" sets out to make the common man fly and in the process takes on the world''s most capital intensive industry and several enemies who stand in his way.', '["Suriya", "Madhavan"]', 'Sudha Kongara', 'https://m.media-amazon.com/images/M/MV5BOTc2ZTlmYmItMDBhYS00YmMzLWI4ZjAtMTI5YTBjOTFiMGEwXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UY98_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('Interstellar', 2014, 'Adventure', 169, 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.', '["Matthew McConaughey", "Anne Hathaway"]', 'Christopher Nolan', 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('Cidade de Deus', 2002, 'Crime', 130, 'In the slums of Rio, two kids'' paths diverge as one struggles to become a photographer and the other a kingpin.', '["K√°tia Lund", "Alexandre Rodrigues"]', 'Fernando Meirelles', 'https://m.media-amazon.com/images/M/MV5BOTMwYjc5ZmItYTFjZC00ZGQ3LTlkNTMtMjZiNTZlMWQzNzI5XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('Sen to Chihiro no kamikakushi', 2001, 'Animation', 125, 'During her family''s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.', '["Daveigh Chase", "Suzanne Pleshette"]', 'Hayao Miyazaki', 'https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('Saving Private Ryan', 1998, 'Drama', 169, 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.', '["Tom Hanks", "Matt Damon"]', 'Steven Spielberg', 'https://m.media-amazon.com/images/M/MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('The Green Mile', 1999, 'Crime', 189, 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.', '["Tom Hanks", "Michael Clarke Duncan"]', 'Frank Darabont', 'https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('La vita e bella', 1997, 'Comedy', 116, 'When an open-minded Jewish librarian and his son become victims of the Holocaust, he uses a perfect mixture of will, humor, and imagination to protect his son from the dangers around their camp.', '["Roberto Benigni", "Nicoletta Braschi"]', 'Roberto Benigni', 'https://m.media-amazon.com/images/M/MV5BYmJmM2Q4NmMtYThmNC00ZjRlLWEyZmItZTIwOTBlZDQ3NTQ1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('Se7en', 1995, 'Crime', 127, 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.', '["Morgan Freeman", "Brad Pitt"]', 'David Fincher', 'https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('The Silence of the Lambs', 1991, 'Crime', 118, 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.', '["Jodie Foster", "Anthony Hopkins"]', 'Jonathan Demme', 'https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX67_CR0,0,67,98_AL_.jpg');
insert into movies(title, released_year, genre, runtime, overview, actors, director, poster) values('Star Wars', 1977, 'Action', 121, 'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire''s world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.', '["Mark Hamill", "Harrison Ford"]', 'George Lucas', 'https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX67_CR0,0,67,98_AL_.jpg');